name: CI
permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies and lint
        run: |
          npm i
          npm ci --legacy-peer-deps
          npm install --no-package-lock --no-save --legacy-peer-deps n8n-workflow@">=2.6.1"
          npm run lint
    
      - name: Run build
        run: 'npm run build'
